#!/bin/sh
#
# @name Scout Drone
# @type Quadrotor x
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=scout_drone}

param set-default SIM_GZ_EN 1

# --- THE FIX: Custom Geometry prevents the NaN crash! ---
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

# --- FAILSAFE KILLERS ---
param set-default NAV_DLL_ACT 0
param set-default NAV_RCL_ACT 0
param set-default CBRK_SUPPLY_CHK 894281
param set-default COM_ARM_MAG_STR 0

# --- GAZEBO ESC MAPPINGS ---
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 2000
param set-default SIM_GZ_EC_MAX2 2000
param set-default SIM_GZ_EC_MAX3 2000
param set-default SIM_GZ_EC_MAX4 2000

param set-default MPC_THR_HOVER 0.60
